#!/usr/bin/env bash
parent_path=$( cd "$(dirname "${BASH_SOURCE[1]}")" ; pwd -P )
new_line="hello"

echo Parent path: $parent_path

# Create temp CSS files in /workflow for merging
sed -s -e $'$a\\\n' $parent_path/abstracts/variables.css > $parent_path/workflow/variables.css
sed -s -e $'$a\\\n' $parent_path/base/normalize.css > $parent_path/workflow/normalize.css
sed -s -e $'$a\\\n' $parent_path/base/reset.css > $parent_path/workflow/reset.css
sed -s -e $'$a\\\n' $parent_path/base/utilities.css > $parent_path/workflow/utilities.css
sed -s -e $'$a\\\n' $parent_path/components/alert/alert.css > $parent_path/workflow/alert.css
sed -s -e $'$a\\\n' $parent_path/components/avatar/avatar.css > $parent_path/workflow/avatar.css
sed -s -e $'$a\\\n' $parent_path/components/badge/badge.css > $parent_path/workflow/badge.css
sed -s -e $'$a\\\n' $parent_path/components/button/button.css > $parent_path/workflow/button.css
sed -s -e $'$a\\\n' $parent_path/components/card/card.css > $parent_path/workflow/card.css
sed -s -e $'$a\\\n' $parent_path/components/image/image.css > $parent_path/workflow/image.css
sed -s -e $'$a\\\n' $parent_path/components/input/input.css > $parent_path/workflow/input.css
sed -s -e $'$a\\\n' $parent_path/components/text-utilities/text-utilities.css > $parent_path/workflow/text-utilities.css
sed -s -e $'$a\\\n' $parent_path/components/rating/rating.css > $parent_path/workflow/rating.css
sed -s -e $'$a\\\n' $parent_path/components/grid/grid.css > $parent_path/workflow/grid.css

# Merge temp CSS files into /styles/foobar-ui.css
cat \
$parent_path/workflow/variables.css \
$parent_path/workflow/normalize.css \
$parent_path/workflow/reset.css \
$parent_path/workflow/utilities.css \
$parent_path/workflow/alert.css \
$parent_path/workflow/avatar.css \
$parent_path/workflow/badge.css \
$parent_path/workflow/button.css \
$parent_path/workflow/card.css \
$parent_path/workflow/image.css \
$parent_path/workflow/input.css \
$parent_path/workflow/text-utilities.css \
$parent_path/workflow/rating.css \
$parent_path/workflow/grid.css \
> $parent_path/styles/foobar-ui.css

sed -i '$ d' $parent_path/styles/foobar-ui.css

# Remove temp CSS files
rm $parent_path/workflow/variables.css
rm $parent_path/workflow/normalize.css
rm $parent_path/workflow/reset.css
rm $parent_path/workflow/utilities.css
rm $parent_path/workflow/alert.css
rm $parent_path/workflow/avatar.css
rm $parent_path/workflow/badge.css
rm $parent_path/workflow/button.css
rm $parent_path/workflow/card.css
rm $parent_path/workflow/image.css
rm $parent_path/workflow/input.css
rm $parent_path/workflow/text-utilities.css
rm $parent_path/workflow/rating.css
rm $parent_path/workflow/grid.css

echo "CSS merging complete"
